### ISSUE TITLE
Windows Qlight?

### ISSUE THREAD

**Issue by coderkan** [viraggada/node-qlight#1]
Hi @viraggada 

This is a good works. Have you any tried on windows machine like this project?

**Comment by viraggada** [comment]
Hello @coderkan 

I have not tried it for Windows but there is a [Windows application](http://www.qlight.com/en/technology-data/usb-tower-lamp/) made available by Qlight.

**Comment by coderkan** [comment]
Hi @viraggada 

Thanks for your reply, 
I have developed **Windows Desktop Application** but I want to control it on **Browser**.
